spring:
  datasource:
    url: jdbc:mysql://localhost:3306/movies_db
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

project:
  poster: posters/

base:
  url: "http://localhost:8080"